FROM quay.io/fedora/fedora-bootc:latest AS bootc

FROM ghcr.io/sigstore/cosign/cosign:v3.1.1 AS cosign

FROM quay.io/fedora/fedora:latest AS builder

ENV USERNAME="ublue"

COPY --from=bootc --chmod=0755 /usr/libexec/bootc-base-imagectl /usr/libexec/bootc-base-imagectl
COPY --from=bootc /usr/share/doc/bootc-base-imagectl /usr/share/doc/
COPY --from=cosign /ko-app/cosign /usr/local/bin/cosign

RUN --mount=type=tmpfs,dst=/var \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=cache,dst=/var/cache/libdnf5 \
    bash <<'RUNEOF'
set -eoux pipefail
dnf5 config-manager setopt install_weak_deps=False keepcache=1
dnf5 copr -y enable ublue-os/packages

dnf5 install -y \
    ShellCheck \
    buildah \
    cpp \
    erofs-utils \
    git \
    golang-oras \
    jq \
    just \
    openssl \
    python3 \
    rpm-ostree \
    sbsigntools \
    selinux-policy-targeted \
    shfmt \
    socat \
    systemd-container \
    tmux \
    ublue-os-signing \
    yq \
    zstd

# syft
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/bin

# macadam
if [[ "$(rpm -E %_arch)" =~ x86_64 ]]; then
    curl --retry 3 -Lo "/usr/bin/macadam" "https://github.com/crc-org/macadam/releases/latest/download/macadam-linux-amd64"
elif [[ "$(rpm -E %_arch)" =~ aarch64 ]]; then
    curl --retry 3 -Lo "/usr/bin/macadam" "https://github.com/crc-org/macadam/releases/latest/download/macadam-linux-arm64"
else
    echo "Unsupported Arch" >&2
    exit 1
fi
chmod +x /usr/bin/macadam
macadam completion bash >/etc/bash_completion.d/macadam.sh

# bootc-base-imagectl
chmod +x /usr/libexec/bootc-base-imagectl

# Cleanup
dnf5 copr -y disable ublue-os/packages
RUNEOF

LABEL \
    "name"="devcontainer" \
    "org.opencontainers.image.name"="devcontainer" \
    "org.opencontainers.image.url"="https://github.com/ublue-os/devcontainer" \
    "org.opencontainers.image.vendor"="Universal Blue" \
    "org.opencontainers.image.version"="base" \
    "vendor"="Universal Blue" \
    "version"="base"

FROM quay.io/coreos/chunkah AS chunkah
RUN --mount=type=bind,target=/run/src,rw \
    --mount=from=builder,target=/chunkah,ro \
      chunkah build --output oci:/run/src/out

FROM oci:out
